backend:
  name: git-gateway
  branch: main

# Local backend configuration
local_backend: true

# Disable authentication for local testing
auth: false

# Media settings
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Collections
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "homepage"
        label: "Homepage"
        file: "src/content/pages/homepage.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Hero Title", name: "heroTitle", widget: "string"}
          - {label: "Hero Description", name: "heroDescription", widget: "text"}
          - {label: "Categories", name: "categories", widget: "list", fields: [
              {label: "Name", name: "name", widget: "string"},
              {label: "Icon", name: "icon", widget: "string"},
              {label: "Link", name: "link", widget: "string"}
            ]}
          - {label: "Latest Articles", name: "latestArticles", widget: "list", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Summary", name: "summary", widget: "text"},
              {label: "Date", name: "date", widget: "datetime"},
              {label: "Link", name: "link", widget: "string"}
            ]}

  - name: "articles"
    label: "Articles"
    folder: "src/content/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "select", options: ["celestial-events", "geological-formations", "historical-figures", "scientific-principles", "tech-concepts"]}
      - {label: "Tags", name: "tags", widget: "list", field: {label: "Tag", name: "tag", widget: "string"}}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "SEO Title", name: "seoTitle", widget: "string", required: false}
      - {label: "SEO Description", name: "seoDescription", widget: "text", required: false}
      - {label: "Schema Markup", name: "schemaMarkup", widget: "object", fields: [
          {label: "Type", name: "type", widget: "select", options: ["Article", "FAQPage", "HowTo", "Product"]},
          {label: "JSON-LD", name: "jsonLd", widget: "text", required: false}
        ]}

  - name: "site-settings"
    label: "Site Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "src/content/site-settings/general.md"
        fields:
          - {label: "Site Title", name: "siteTitle", widget: "string"}
          - {label: "Site Description", name: "siteDescription", widget: "text"}
          - {label: "Brand Colors", name: "brandColors", widget: "object", fields: [
              {label: "Primary", name: "primary", widget: "string", default: "#0284c7"},
              {label: "Secondary", name: "secondary", widget: "string", default: "#64748b"}
            ]}
          - {label: "Footer Text", name: "footerText", widget: "text"}
          - {label: "Footer Tagline", name: "footerTagline", widget: "text"}
